version: "3"
services:
    mongodb:
        container_name: mongo-dev
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_DATABASE=auth
            - MONGO_INITDB_ROOT_PASSWORD=admin
        ports:
            - "27017:27017"
        volumes:
            - $HOME/docker/volumes/mongodb:/var/lib/mongodb/data
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        depends_on:
            - mongodb
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
            - ME_CONFIG_MONGODB_SERVER=mongo-dev
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
        ports:
            - "8081:8081"
    postgres:
        container_name: postgres
        image: postgres
        environment:
            - POSTGRES_PASSWORD=123456
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql